library(dplyr)
library(demutils)

db <- pg_connect()

create_methodology()

# replace methodology.pdf in autogenerated_refs
system("cp ~/proj/demscore/reference_documents/demscoremethodology/methodology.pdf ~/data/demscore_next_release/autogenerated_refs/static/methodology.pdf")