library(dplyr)
library(demutils)

db <- pg_connect()

#==============================================================================
# The purpose of this script is to extract and add all unit identifier columns
# to the PostgreSQL database. The unit identifier variables appear in the
# autogenerated codebooks.

# This script should be run before each version update of Demscore. 
#==============================================================================


#==============================================================================
# 1. Load all datasets and extract only unit columns from each dataset. Keep 
# distinct unit columns as we only need each unit column once in the harmonized 
# meta data.
#==============================================================================
datasets <- DBI::dbGetQuery(db, "SELECT * FROM datasets;")

tags <- c(datasets$tag)
ll <- lapply(tags, read_datasets, db)

names(ll) = tags

all_ucols <- Map(function(l, nms) {
  
  u_cols <- colnames(l)[grepl("^u_", x = colnames(l))]
  out_df <- data.frame(u_cols = u_cols, ds = nms)
  return(out_df)
  
}, l = ll, nms = names(ll)) %>% 
  do.call(what = rbind.data.frame, args = .)

ucols <- all_ucols %>% distinct(u_cols) 

#==============================================================================
# 2. Load relevant tables
#==============================================================================

unit_cols <- DBI::dbGetQuery(db, "SELECT * FROM unit_variables;")

new_ucols <- left_join(ucols, unit_cols, by = c("u_cols" = "tag")) %>% 
  filter(is.na(unit_variables_id)) 

uv_id_latest_rn <- 
  unit_cols %>% 
  data.frame() %>%
  filter(unit_variables_id == max(unit_variables_id)) %>%
  select(unit_variables_id) %>%
  pull(unit_variables_id)

id_start <- uv_id_latest_rn+1
id_end <- uv_id_latest_rn+nrow(new_ucols)

#==============================================================================
# 3. Prepare dataframe to be appended to postgres table
#==============================================================================

final_unit_vars <- new_ucols %>%
  filter(is.na(unit_variables_id)) %>%
  mutate(tag = tag,
         unit_tag = unit_tag,
         cb_entry = "", 
         name = "Demscore Unit Identifier taken from ",
         unit_variables_id = id_start:id_end)

check <- final_unit_vars %>% filter(is.na(tag))


#==============================================================================
# 6. CAREFULLY update the PostgreSQL database
#============================================================================== 

###### DONT RUN AGAIN UNLESS YOU ARE SURE EVERYTHING LOOKS FINE ########

pg_append_table(final_unit_vars, "unit_variables", db)
