

suppressMessages(library(docopt))
suppressMessages(library(dplyr))
suppressMessages(library(demutils))

source("~/proj/demscore/.Rprofile")

db <- pg_connect()
variables <- tbl(db, "variables") %>% collect(n = Inf)
df <- variables %>% filter(grepl("^vdem_ert|complab_grace_|ucdp_orgv_cy_sb_|repdem_paged_paco", tag_long), is.na(head_var))


# Parse docopt string arguments and options
args <- list(help = FALSE,
			 include_unit_cols = TRUE,
			 file_format = "R",
			 remove_empty_rows = TRUE,
			 output_unit_tag = "u_qog_country_year",
			 outfile = "~/data/demscore_next_release/autogenerated_refs/build/data.zip",
			 variables = df$tag_long)

envir <- list(
	POSTGRES_TABLES_DIR = POSTGRES_TABLES_DIR, 
	REF_STATIC_DIR = REF_STATIC_DIR, 
	UNIT_DATA_DIR = UNIT_DATA_DIR, 
	LOCAL = LOCAL, 
	UNIT_TABLE_DIR = UNIT_TABLE_DIR)

prepare_autogen()

# Functions
proc <- proc.time()
generate_zip(args, envir)
proc.time() - proc

df <- read_file("~/data/demscore_next_release/autogenerated_refs/build/data/data.rds")
