

suppressMessages(library(docopt))
suppressMessages(library(dplyr))
suppressMessages(library(demutils))

source("~/proj/demscore/.Rprofile")

db <- pg_connect()
variables <- tbl(db, "variables") %>% collect(n = Inf) %>% filter(active)
df <- variables %>% filter(grepl("^complab_spin_cbd|^qog_std_ts_ti_cpi", tag_long), is.na(head_var))


# Parse docopt string arguments and options
args <- list(help = FALSE,
			 include_unit_cols = TRUE,
			 file_format = "R", 
			 remove_empty_rows = TRUE,
			 output_unit_tag = "u_demscore_country_year",
			 outfile = "~/data/demscore_next_release/autogenerated_refs/build/data.rds",
			 variables = df$tag_long)

# Functions
proc <- proc.time()
generate_data(args, POSTGRES_TABLES_DIR, UNIT_DATA_DIR, LOCAL,
	UNIT_TABLE_DIR, prep = FALSE)
proc.time() - proc

# Check how it looks
df2 <- read_file("~/data/demscore_next_release/autogenerated_refs/build/data.rds")

df[df == -11111] = NA

#Check for stat labels after reading file
attr(df, "var.labels")
