library(dplyr)
library(demutils)

db <- pg_connect()

# The Download Interface unit selectors for these units are Location and Year

# Truncate table, set counter to 1
pg_send_query(db, "TRUNCATE conflict_location_years;")

# Set counter to 1
pg_send_query(db, 
              "SELECT setval('conflict_location_years_conf_year_id_seq', 1, false);")

variables <- readRDS(file.path(
  Sys.getenv("ROOT_DIR"), "autogenerated_refs", "refs_prepped", "variables.rds"))

units_online <- DBI::dbGetQuery(db, "SELECT * FROM units;")


# Country-year units
CY_UNITS <- units_online %>%
  filter(unit_id %in% c(19, 26, 39)) %$% unit_tag

## merge in conflict names
lapply(CY_UNITS, function(u) {
  # u <- CY_UNITS[3]
  
  print(u)
  
  utable <- read_unit_table(u)
  UNIT_ID <- units_online$unit_id[units_online$unit_tag == u]
  stopifnot(!is.na(UNIT_ID))
  
  units_filtered <- units_online %>% filter(unit_id == UNIT_ID)
  location_col <- units_filtered$location_col
  year_col <- units_filtered$year_col
  
  
  stopifnot(!is.na(year_col), !is.na(location_col))
  stopifnot(year_col %in% names(utable), location_col %in% names(utable))
  
  names(utable)[names(utable) == location_col] <- "location"
  names(utable)[names(utable) == year_col] <- "year"
  
  # Select only country_name
  utable %<>% distinct(location, year)
  class(utable) <- "data.frame"
  
  utable$unit_id <- UNIT_ID
  
  #pg_send_query(db, 
  #              paste0("DELETE FROM temp WHERE unit_id = ", 
  #                     UNIT_ID, ";"))
  pg_append_table(utable, "temp", db)
  
})
  
  
## Create lookup table
cly <- DBI::dbGetQuery(db, "SELECT * FROM temp")

pg_send_query(db, "DROP TABLE IF EXISTS temp;")
pg_send_query(db, "TRUNCATE location_lookup;")
  
unique_loc <- unique(cly$location)
    
location_lookup <- data.frame(
  location_id = 1:length(unique_loc),
  location_name = unique_loc
) %>%
  distinct(location_id, .keep_all = TRUE)

pg_append_table(location_lookup, "location_lookup", db)

cly_new <- left_join(cly, location_lookup, by = c("location" = "location_name"))
cly_new %<>% select(-location)

pg_append_table(cly_new, "conflict_location_years", db)
  

DBI::dbDisconnect(db)