library(dplyr)
library(demutils)

db <- pg_connect()

# Truncate table, set counter to 1
# TRUNCATE region_years
pg_send_query(db, "TRUNCATE region_years;")

# Set counter to 1
pg_send_query(db, 
              "SELECT setval('region_years_ry_id_seq', 1, false);")

variables <- readRDS(file.path(
  Sys.getenv("ROOT_DIR"), "autogenerated_refs", "refs_prepped", "variables.rds"))

units_online <- DBI::dbGetQuery(db, "SELECT * FROM units;")

# region-year units
CY_UNITS <- units_online %>%
  filter(unit_id %in% c(57)) %$% unit_tag


lapply(CY_UNITS, function(u) {
  # u <- CY_UNITS[1]
  
  print(u)
  
  utable <- read_unit_table(u)
  UNIT_ID <- units_online$unit_id[units_online$unit_tag == u]
  stopifnot(!is.na(UNIT_ID))
  
  units_filtered <- units_online %>% filter(unit_id == UNIT_ID)
  region_col <- units_filtered$region_col
  year_col <- units_filtered$year_col
  
  
  stopifnot(!is.na(year_col), !is.na(region_col))
  stopifnot(year_col %in% names(utable), 
            region_col %in% names(utable))
  
  names(utable)[names(utable) == region_col] <- "region_name"
  names(utable)[names(utable) == year_col] <- "year"
  
  # Select only region_name
  utable %<>% distinct(region_name, year)
  class(utable) <- "data.frame"
  
  utable$unit_id <- UNIT_ID
  
  pg_send_query(db, 
                paste0("DELETE FROM region_years WHERE unit_id = ", 
                       UNIT_ID, ";"))
  pg_append_table(utable, "region_years", db)
  
})

DBI::dbDisconnect(db)