library(dplyr)
library(demutils)

db <- pg_connect()

# Truncate table, set counter to 1
# TRUNCATE country_years
pg_send_query(db, "TRUNCATE country_years;")

# Set counter to 1
pg_send_query(db, 
              "SELECT setval('country_years_cy_id_seq', 1, false);")

variables <- readRDS(file.path(
  Sys.getenv("ROOT_DIR"), "autogenerated_refs", "refs_prepped", "variables.rds"))

units_online <- tbl(db, "units") %>% collect(n = Inf)

# Country-year units
CY_UNITS <- units_online %>%
  filter(unit_id %in% c(44, 34, 23, 106, 1, 101, 8, 111)) %$% unit_tag


lapply(CY_UNITS, function(u) {
  # u <- CY_UNITS[1]
  
  print(u)
  
  utable <- read_unit_table(u)
  UNIT_ID <- units_online$unit_id[units_online$unit_tag == u]
  stopifnot(!is.na(UNIT_ID))
  
  units_filtered <- units_online %>% filter(unit_id == UNIT_ID)
  country_col <- units_filtered$country_col
  year_col <- units_filtered$year_col
  
  
  stopifnot(!is.na(year_col), !is.na(country_col))
  stopifnot(year_col %in% names(utable), country_col %in% names(utable))
  
  names(utable)[names(utable) == country_col] <- "country_name"
  names(utable)[names(utable) == year_col] <- "year"
  
  # Select only country_name
  utable %<>% distinct(country_name, year)
  class(utable) <- "data.frame"
  
  utable$unit_id <- UNIT_ID

  pg_send_query(db, 
                paste0("DELETE FROM country_years WHERE unit_id = ", 
                       UNIT_ID, ";"))
  pg_append_table(utable, "country_years", db)
  
})

DBI::dbDisconnect(db)